# -*- coding: utf-8 -*-
"""Football's Great Wall in The First Half of 2025-2026 Season

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCLrG1_Hr7u5HNQVBzkLsmcoloJbobIR
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('players_data-2025_2026.csv')
df.head()

# Data Frame Check

df.info()

# All Data Frame Column Check

df.columns

# Goalkeeper Filter

df_gk = df[df['Pos'] == 'GK'].copy()
df_gk.head()

# Goalkeeper Data Frame Column Check

df_gk.info()

# Goalkeeper Match Played Data Check

df_gk['MP'].describe()

# Goalkeeper Minutes Played Data Check

df_gk['Min'].describe()

# Goalkeeper Baseline Filter

baseline_min = df_gk['Min'].median()

df_gk_filtered = df_gk[df_gk['Min'] >= baseline_min].copy()

print("Sebelum filter:", df_gk.shape[0])
print("Sesudah filter:", df_gk_filtered.shape[0])

# Goalkeeper Minutes Played After Filter

df_gk_filtered['Min'].describe()

# Visualization Goalkeeper Minutes Played Filter

minutes = df_gk_filtered['Min']

plt.figure(figsize=(6, 2))
plt.boxplot(minutes, vert=False)

plt.title('Boxplot of Goalkeeper Minutes Played')
plt.xlabel('Minutes Played')
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

# Goalkeeper Filter Validation

df_gk_filtered['Min_per_MP'] = (
    df_gk_filtered['Min'] / df_gk_filtered['MP']
)

df_gk_filtered = df_gk_filtered[
    df_gk_filtered['Min_per_MP'] >= 85
]

df_gk_filtered.info()

# Goalkeeper Filter List Check

df_gk_filtered.sort_values('Min').head(5)[
    ['Player', 'Squad', 'Min', 'MP']
]

# Goalkeeper Filter Cleaning

df_gk_filtered.reset_index(drop=True, inplace=True)

df_gk_filtered.head()

# Goalkeeper Data Clean Check

df_gk_filtered.info()

# Goalkeeper League Origin Check

df_gk_filtered['Comp'].value_counts()

# Visualization Sample Distribution

league_counts = df_gk_filtered['Comp'].value_counts()

plt.figure(figsize=(6, 6))
plt.pie(
    league_counts,
    labels=league_counts.index,
    autopct='%1.1f%%',
    startangle=90
)

plt.title('Goalkeeper Sample Distribution by League (%)')
plt.tight_layout()
plt.show()

# Goalkeeper Feature/Metric Check

cols = ['GA', 'Saves', 'CS', 'PKsv', 'PrgP', 'Save%', 'Cmp%']
df_gk_filtered[cols].info()

# Defining Goalkeeper Feature/Metric Normalization

per90_metrics = ['GA', 'Saves', 'CS', 'PKsv', 'PrgP']

for col in per90_metrics:
    df_gk_filtered[f'{col}_per90'] = (
        df_gk_filtered[col] / df_gk_filtered['Min'] * 90
    )

df_gk_filtered[[f'{c}_per90' for c in per90_metrics]].describe()

# Visualization Goalkeeper Feature/Metric Normalization

per90_cols = [f'{c}_per90' for c in per90_metrics]

for col in per90_cols:
    plt.figure(figsize=(6,4))
    plt.hist(df_gk_filtered[col], bins=20)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.grid(alpha=0.3)
    plt.show()

# Goalkeeper Feature/Metric Scale Normalization

metrics_for_scaling = [
    'GA_per90', 'Saves_per90', 'CS_per90',
    'Save%',
    'PKsv_per90', 'PrgP_per90',
    'Cmp%'
]

for col in metrics_for_scaling:
    df_gk_filtered[f'{col}_z'] = (
        df_gk_filtered[col] - df_gk_filtered[col].mean()
    ) / df_gk_filtered[col].std()

df_gk_filtered[
    [col for col in df_gk_filtered.columns if col.endswith('_z')]
].describe().round(3)

# Z-Score Definition

z_metrics = [
    'GA_per90_z',
    'Saves_per90_z',
    'CS_per90_z',
    'Save%_z',
    'PKsv_per90_z',
    'PrgP_per90_z',
    'Cmp%_z'
]

df_gk_filtered[z_metrics].head()

# Visualization Goalkeeper Feature/Metric Scale Normalization

z_cols = [col for col in df_gk_filtered.columns if col.endswith('_z')]

for col in z_cols:
    plt.figure(figsize=(6,4))
    plt.hist(df_gk_filtered[col], bins=20)
    plt.axvline(0, linestyle='--')
    plt.title(f'Distribution of {col}')
    plt.xlabel('Z-Score')
    plt.ylabel('Frequency')
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()

# Visualization Goalkeeper Feature/Metric Scale Normalization

means = df_gk_filtered[z_cols].mean()
stds = df_gk_filtered[z_cols].std()

plt.figure(figsize=(8,4))
plt.bar(means.index, means.values)
plt.axhline(0)
plt.title('Mean of Z-Score Metrics')
plt.xticks(rotation=45)
plt.grid(axis='y', alpha=0.3)
plt.show()

plt.figure(figsize=(8,4))
plt.bar(stds.index, stds.values)
plt.axhline(1)
plt.title('Standard Deviation of Z-Score Metrics')
plt.xticks(rotation=45)
plt.grid(axis='y', alpha=0.3)
plt.show()

# Visualization Goalkeeper Feature/Metric Scale Normalization

plt.figure(figsize=(8,5))
plt.boxplot(df_gk_filtered[z_cols])
plt.xticks(range(1, len(z_cols)+1), z_cols, rotation=45)
plt.title('Boxplot of Z-Score Normalized Metrics')
plt.tight_layout()
plt.show()

# Reverse Negative Feature/Metric

df_gk_filtered['GA_per90_z'] *= -1

# Feature/Metric Grouping

group_map = {
    'Save%_z': 'shot',
    'Saves_per90_z': 'shot',
    'PKsv_per90_z': 'shot',

    'GA_per90_z': 'outcome',
    'CS_per90_z': 'outcome',

    'PrgP_per90_z': 'dist',
    'Cmp%_z': 'dist'
}

# Feature/Metric Grouping Distribution

group_target = {
    'shot': 0.70,
    'outcome': 0.20,
    'dist': 0.10
}

# PCA

from sklearn.decomposition import PCA

X = df_gk_filtered[z_metrics]
pca = PCA()
pca.fit(X)

weights = abs(pca.components_[0])
weights = weights / weights.sum()

pd.Series(weights, index=z_metrics)

# Visualization PCA

explained_var = pca.explained_variance_ratio_

plt.figure()
plt.plot(range(1, len(explained_var)+1), explained_var, marker='o')
plt.title('PCA Explained Variance Ratio')
plt.xlabel('Principal Component')
plt.ylabel('Explained Variance Ratio')
plt.grid(True)
plt.show()

# Visualization PCA

weights_original = abs(pca.components_[0])
weights_original = weights_original / weights_original.sum()

weights_original_series = pd.Series(weights_original, index=z_metrics)

plt.figure()
weights_original_series.plot(kind='bar')

plt.title('PCA Original Weights (PC1)')
plt.ylabel('Weight')
plt.xticks(rotation=45)
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

print(weights_original_series)

# Goalkeeper Performance Index

weights_pca = pd.Series({
    'GA_per90_z': 0.259521,
    'Saves_per90_z': 0.107717,
    'CS_per90_z': 0.253406,
    'Save%_z': 0.180443,
    'PKsv_per90_z': 0.010548,
    'PrgP_per90_z': 0.041944,
    'Cmp%_z': 0.146421
})

df_gk_filtered['GK_Index'] = (
    df_gk_filtered[weights_pca.index] * weights_pca
).sum(axis=1)

# Visualization Goalkeeper Performance Index

plt.figure()
plt.hist(df_gk_filtered['GK_Index'], bins=20)
plt.axvline(df_gk_filtered['GK_Index'].mean(), linestyle='--')
plt.title('Distribution of GK_Index')
plt.xlabel('GK_Index')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

# PCA Re-Scaling

weights_adjusted = weights_pca.copy()

for group in group_target:
    cols = [m for m, g in group_map.items() if g == group]
    current_sum = weights_pca[cols].sum()
    weights_adjusted[cols] = (
        weights_pca[cols] / current_sum * group_target[group]
    )

# Visualization PCA After Re-Scaling

plt.figure()
weights_adjusted.plot(kind='bar')

plt.title('PCA Adjusted Weights')
plt.ylabel('Weight')
plt.xticks(rotation=45)
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

print(weights_adjusted)

# Visualization PCA Comparison

comparison_df = pd.DataFrame({
    'Original_PCA': weights_original_series,
    'Adjusted_PCA': weights_adjusted
})

plt.figure()
comparison_df.plot(kind='bar')

plt.title('Original vs Adjusted PCA Weights')
plt.ylabel('Weight')
plt.xticks(rotation=45)
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

print(comparison_df)

# Goalkeeper Index Final

df_gk_filtered['GK_Index_adj'] = (
    df_gk_filtered[weights_adjusted.index] * weights_adjusted
).sum(axis=1)

# Visualization Goalkeeper Index Final

plt.figure()
plt.hist(df_gk_filtered['GK_Index_adj'], bins=20)
plt.axvline(df_gk_filtered['GK_Index_adj'].mean(), linestyle='--')
plt.title('Distribution of GK_Index_adj')
plt.xlabel('GK_Index_adj')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

# Visualization Comparison Index Before-After

x = df_gk_filtered['GK_Index']
y = df_gk_filtered['GK_Index_adj']

plt.figure(figsize=(6,6))
plt.scatter(x, y)

# garis diagonal
min_val = min(x.min(), y.min())
max_val = max(x.max(), y.max())
plt.plot([min_val, max_val], [min_val, max_val])

plt.xlabel("GK_Index (Before)")
plt.ylabel("GK_Index_adj (After)")
plt.title("Index Before vs After Re-scaling")

plt.grid(alpha=0.3)
plt.show()

# tampilkan korelasi
print("Correlation:", df_gk_filtered[['GK_Index','GK_Index_adj']].corr().iloc[0,1])

# Goalkeeper Index Adj Validation 1

df_gk_filtered[['GK_Index_adj', 'CS_per90']].corr()

# New Goalkeeper Index Validation 2

df_gk_filtered[['GK_Index_adj', 'Saves_per90']].corr()

# Goalkeeper Ranking

df_ranked = (
    df_gk_filtered
    .sort_values('GK_Index_adj', ascending=False)
    .reset_index(drop=True)
)

df_ranked[['Player', 'Squad', 'Comp', 'GK_Index_adj']].head(75)

# Goalkeeper Tier Segmentation

df_gk_filtered['Tier'] = pd.qcut(
    df_gk_filtered['GK_Index_adj'],
    q=[0, 0.25, 0.75, 0.95, 1.0],
    labels=['Below Average', 'Average', 'Strong', 'Elite']
)

# Visualization Goalkeeper Tier Segmentation

tier_counts = df_gk_filtered['Tier'].value_counts().sort_index()

plt.figure()
plt.bar(tier_counts.index.astype(str), tier_counts.values)

plt.title('Goalkeeper Tier Distribution')
plt.xlabel('Tier')
plt.ylabel('Number of Goalkeepers')

plt.xticks(rotation=45)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

tier_percentage = df_gk_filtered['Tier'].value_counts(normalize=True).sort_index()

plt.figure()
plt.pie(
    tier_percentage.values,
    labels=tier_percentage.index.astype(str),
    autopct='%1.1f%%'
)

plt.title('Goalkeeper Tier Percentage Distribution')
plt.tight_layout()
plt.show()

# Tier Validation


plt.title('Tier Validation')
df_gk_filtered['GK_Index_adj'].hist()

# Tier Summary

tier_summary = df_gk_filtered.groupby('Tier')[[
    'GA_per90',
    'Saves_per90',
    'CS_per90',
    'Save%',
    'PKsv_per90',
    'PrgP_per90',
    'Cmp%'
]].mean().round(3)

tier_summary

# Elite Goalkeeper Index Decomposition

elite_gk = df_gk_filtered[df_gk_filtered['Tier'] == 'Elite'].copy()

elite_gk = elite_gk.sort_values('GK_Index_adj', ascending=False).reset_index(drop=True)

elite_gk.head(10)

for tier in df_gk_filtered['Tier'].unique():
    print(f"\n===== {tier} =====")
    display(
        df_gk_filtered[df_gk_filtered['Tier'] == tier][
            ['Player', 'Comp', 'GK_Index_adj']
        ].sort_values(by='GK_Index_adj', ascending=False).reset_index(drop=True)
    )

# Goalkeeper Data After EDA

Full_Goalkeeper_List = (
    df_gk_filtered
    .sort_values('GK_Index_adj', ascending=False)
    .reset_index(drop=True)
)

Full_Goalkeeper_List.head(75)

# Data Conversion & Download

from google.colab import auth
auth.authenticate_user()

import gspread
from gspread_dataframe import set_with_dataframe
from google.auth import default

creds, _ = default()
gc = gspread.authorize(creds)

# Buat spreadsheet baru
sh = gc.create("Goalkeeper Final Ranking")

# Pilih sheet pertama
worksheet = sh.get_worksheet(0)

# Kirim dataframe
set_with_dataframe(worksheet, Full_Goalkeeper_List)

print("Google Sheet URL:", sh.url)